export const events = {
  TIMEOUT_ENTER_WEBAPI: 'TIMEOUT_ENTER_WEBAPI',
  TIMEOUT_ENTER_STACK: 'TIMEOUT_ENTER_STACK',
  TIMEOUT_FINISH: 'TIMEOUT_FINISH',

  FN_ENTER_CALLSTACK: 'NORMAL_ENTER_CALLSTACK',
  FN_EXIT_CALLSTACK: 'NORMAL_EXIT_CALLSTACK',

  CONSOLE_LOG: 'CONSOLE',
  EVENT_LOOP: 'EVENT_LOOP',
  QUEUEMICROTASK_ENTER_STACK: 'QUEUEMICROTASK_ENTER_STACK',
  QUEUEMICROTASK_ENTER_MICROTASK: 'QUEUEMICROTASK_ENTER_MICRO_STACK',
  QUEUEMICROTASK_FINISH: 'QUEUEMICROTASK_FINISH',
};
